### ISSUE TITLE
Send notification emails

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/versions-france-elections#1]
- [x] Create new list on SIB
- [ ] Add emails to this list
- [x] Create custom email template in french with good version urls

**Comment by martinratinaud** [comment]
@MattiSG please provide the emails I should add to it
Thanks

**Comment by martinratinaud** [comment]
@MattiSG 
Just added myself and you (on your beta address as it already existed in SIB) to this mailing list

Once merge is done on core, we should receive emails.

You can then add anybody directly on https://my.sendinblue.com/users/list/id/466

**Comment by martinratinaud** [comment]
Just received my first email from elections-france
clicked both link and button and it works fine
